### ISSUE TITLE
Are modded items not supported?

### ISSUE THREAD

**Issue by beans-squared** [mikaelsrozee/drops#2]
I am attempting to setup drops that include gun magazines from Techguns, however the game crashes with the error described in this crash report:
[https://pastebin.com/35Z7p0HV](https://pastebin.com/35Z7p0HV)
This is my current config file:
[https://pastebin.com/TUdPj3BZ](https://pastebin.com/TUdPj3BZ)
Are modded item not supported in the drops, or is it that item metadata is not supported?
Thanks.

**Comment by msrcodes** [comment]
The config currently doesn't support metadata ids as this is fixed in [1.13's Flattening](https://minecraft.gamepedia.com/Java_Edition_1.13/Flattening). You may be able to get around this using NBT data.

Either way, 1.12 will not be supported going forward.
